import re
import os
import pandas as pd
from agents.email_service import send_email_with_attachment

try:
    from agents.Report_Agent import handle_report
except ImportError:
    from Report_Agent import handle_report

def handle_email(user_query):
    """
    Handles email requests from user queries.
    Generates report dynamically in txt, csv, or xlsx based on user prompt.
    """
    # Extract email
    email_match = re.search(r"[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+", user_query)
    if not email_match:
        return "Please provide a valid email address."
    to_email = email_match.group()

    # Generate report
    report_data = handle_report(user_query)

    # Determine attachment type
    attachment_type = "txt"
    if ".csv" in user_query.lower() or "csv" in user_query.lower():
        attachment_type = "csv"
    elif ".xlsx" in user_query.lower() or "excel" in user_query.lower() or "xlsx" in user_query.lower():
        attachment_type = "xlsx"

    # Temp folder
    attachment_dir = "temp_reports"
    os.makedirs(attachment_dir, exist_ok=True)
    attachment_path = os.path.join(attachment_dir, f"Drone_Report.{attachment_type}")

    # Generate file correctly based on requested type
    if attachment_type == "txt":
        with open(attachment_path, "w", encoding="utf-8") as f:
            if isinstance(report_data, str):
                f.write(report_data)
            elif isinstance(report_data, list):
                for item in report_data:
                    f.write(", ".join(f"{k}: {v}" for k, v in item.items()) + "\n")
            else:
                f.write(str(report_data))

    elif attachment_type == "csv":
        if isinstance(report_data, str):
            df = pd.DataFrame({"Report": [report_data]})
        else:
            df = pd.DataFrame(report_data)
        df.to_csv(attachment_path, index=False, encoding="utf-8-sig")

    elif attachment_type == "xlsx":
        if isinstance(report_data, str):
            df = pd.DataFrame({"Report": [report_data]})
        else:
            df = pd.DataFrame(report_data)
        df.to_excel(attachment_path, index=False, engine="openpyxl")

    # Email content
    subject = "Aero AI Drone Intelligence Report"
    body = f"""
                Hello,

                Please find the attached drone intelligence report generated by Aero AI system.

                Regards,
                Aero_Drone AI Team
            """

    # Send email
    return send_email_with_attachment(
        to_email,
        subject,
        body,
        attachment_path
    )
